export const UPDATE_TIME = 'UPDATE_TIME';

export const EVENTS_SET = 'EVENTS_DET';

export const DATE_PICKER_SET_DATE_TIME = 'PICKER_SET_DATE_TIME';
export const DATE_PICKER_PICK_YEAR = 'PICKER_PICK_YEAR';
export const DATE_PICKER_PICK_MONTH = 'PICKER_PICK_MONTH';
export const DATE_PICKER_PICK_DAY = 'PICKER_PICK_DAY';
export const DATE_PICKER_PICK_TIME = 'PICKER_PICK_TIME';

export const TEXT_INPUT_CHANGE = 'TEXT_INPUT_CHANGE';

export const SNACKBAR_SHOW = 'SNACKBAR_SHOW';
export const SNACKBAR_HIDE = 'SNACKBAR_HIDE';
