export const UPDATE_TIME = 'UPDATE_TIME';

export const EVENT_ADD = 'EVENT_ADD';
export const EVENT_DELETE = 'EVENT_DELETE';

export const DATE_PICKER_SET_DATE_TIME = 'PICKER_SET_DATE_TIME';
export const DATE_PICKER_PICK_YEAR = 'PICKER_PICK_YEAR';
export const DATE_PICKER_PICK_MONTH = 'PICKER_PICK_MONTH';
export const DATE_PICKER_PICK_DAY = 'PICKER_PICK_DAY';
export const DATE_PICKER_PICK_TIME = 'PICKER_PICK_TIME';

export const TEXT_INPUT_CHANGE = 'TEXT_INPUT_CHANGE';
